# Site settings
title: Inertial Navigation Transformer
description: >- # this means to ignore newlines
  A description for the Inertial Navigation Transformer project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tonton-golio.github.io/inertial_navigation_transformer" # the base hostname & protocol for your site
github_username: tonton-golio

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
remote_theme: "pmarsceill/just-the-docs@v0.3.3"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Just the Docs settings
# This section is specific to the "Just the Docs" theme
just_the_docs:
  search_enabled: true
  search_full_content: true
  aux_links:
    "GitHub Repo":
      - "https://github.com/tonton-golio/inertial_navigation_transformer"
  color_scheme: dark

# Syntax highlighting
# This section configures the Rouge syntax highlighting library
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    css_class: 'highlight'
    line_numbers: true
    line_number_start: 1

# Custom CSS
# Create a file named _sass/custom/custom.scss and add your custom CSS styles
custom_sass: assets/custom.scss