# Site settings
title: Inertial Navigation Transformer

description: >- # this means to ignore newlines
  A description for the Inertial Navigation Transformer project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tonton-golio.github.io/inertial_navigation_transformer" # the base hostname & protocol for your site


# _config.yml

theme: jekyll-theme-minimal

# Dark theme

colorscheme: dark

# Code formatting

code_style:
  indent_style: space
  indent_size: 2
  line_width: 80
  max_nesting: 4

# Other settings

github_pages:
  branch: gh-pages
  Jekyll:
    version: 3.9.0